app = 'airport-chat'
primary_region = 'cdg'

[build]

[env]
  RAILS_ENV = 'production'
  RAILS_SERVE_STATIC_FILES = 'true'
  RAILS_LOG_TO_STDOUT = 'true'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "data"
  destination = "/app/storage"
